export enum UserErrors {
  NO_USER_FOUND = "NO_USER_FOUND",
  WRONG_CREDENTIALS = "WRONG_CREDENTIALS",
  FULLNAME_TAKEN = "FULLNAME_TAKEN",
}

export enum ProductErrors {
  NO_PRODUCT_FOUND = "NO_PRODUCT_FOUND",
  NOT_ENOUGH_STOCK = "NOT_ENOUGH_STOCK",
  INVALID_QUANTITY = "INVALID_QUANTITY",
}
