export enum UserErrors {
  NO_USER_FOUND = "NO_USER_FOUND",
  WRONG_CREDENTIALS = "WRONG_CREDENTIALS",
  FULLNAME_TAKEN = "FULLNAME_TAKEN",
  EMAIL_TAKEN = "EMAIL_TAKEN",
  PHONE_TAKEN = "PHONE_TAKEN",
  USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",
}

export enum ProductErrors {
  NO_PRODUCT_FOUND = "NO_PRODUCT_FOUND",
  NOT_ENOUGH_STOCK = "NOT_ENOUGH_STOCK",
  INVALID_QUANTITY = "INVALID_QUANTITY",
}
